# i don't actually know exactly what's going in these yet,
# so here's just some random values lol
---
number: 7
numbers: [0, 1, 1, 2, 3, 5 ,8]
string: this is a string
strings:
  - According to all known laws of aviation,
  - there is no way a bee should be able to fly.
  - Its wings are too small to get its fat little body off the ground. 