---
Axle:
  WheelIDs: [
    [0,1],    # front
    [2,3]     # rear
  ]
Frame: 
  - LongAxis: 4
  - LatAxis: 0
  - VertAxis: 2
RigidBody:
  - Mass: 1
Scale:
  - Scale: 1
Wheel:
  Position: [
    [0,0,0],
    [0,0,0],
    [0,0,0],
    [0,0,0]
  ]
  Radius: 0.5
  Width: 0.25

  MomentOfInertia: 1.0  # wheel's moment of inertia about the rolling axis.
                        # high value -> less wheel spin when accelerated
  
  DampingRate: 0.25     # how quickly a freely spinning wheel will come to rest:
  
  MaxBrakeTorque: null  # value of torque applied to the wheel when max brake
                        # high value -> lock wheel quicker when braking
                        # lower value -> take longer to lock the wheel
                      
  MaxSteerAngle: null    
Suspension:
  SpringMass: null

  MaxComp: null      # total travel distance along spring direction
  MaxDroop: null     # = MaxComp + MaxDroop

  DampingRate: null
TireForce:
  LongStiffness: null
  LatStiffnessX: null
  LatStiffnessY: null
  FrictionVsSlip: [   
    [0.0, 1.0],
    [0.5, 1.0],
    [1.0, 1.0]
  ]