name: Build and lint the game project
on:
  pull_request:
    branches: [ main ]

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: './game/src'
          extensions: 'h,cpp'
          clangFormatVersion: 15

      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: clang-format
      #     version: 2

      # - name: clang-format
      #   run: |
      #     clang-format --version
      #     find game/src/ -iname *.h -o -iname *.cpp | xargs clang-format --dry-run --Werror --style=file
  
  # build:
  #   name: Build game
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true

  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         vsversion: "2019"
